name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to the main branch

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Choose your preferred Java version
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build
